### PR TITLE
Reduce final image size

### PR DESCRIPTION
**Pull request by desaias**
Using containership/alpine-node-yarn:3.5-6.9.2-0.18.1 and other Dockerfile updates to reduce final image size

Before: 225 MB
After Dockerfile Cleanup: 165 MB

### CODE REVIEW

**Comment by nicktate** [comment]
can you update to node 6.9.3
@desaias

**Comment by nicktate** [comment]
and can you put image size numbers before and after in the PR description

**Comment by desaias** [comment]
I've created a patch request with the Alpine Linux Package to update nodejs to 6.9.3

**Comment by normanjoyner** [comment]
@desaias can you please separate the `Dockerfile` changes and lodash changes into separate PRs?

**Comment by desaias** [comment]
@nicktate I will PR the loadash changes separately

**Pull request merged**
