### PR TITLE
Resurrected Ohai.

### PR DESCRIPTION
**Pull request by jeremykross**
@normanjoyner or @nicktate 

In reference to #171, I think this should bring ohai back to life.

### CODE REVIEW

**Comment by normanjoyner** [comment]
@jeremykross do you have an idea of how this affects our image size?

**Comment by jeremykross** [comment]
@normanjoyner - builds on my machine are coming in at + ~41 megs.

342.4 vs 383 MB

The gem install was failing without all the packages present here - If you think it's prudent, I can `apk del` all of them but rdoc and the basic ohai command still seems to work after installation.

**Comment by normanjoyner** [comment]
I think it's probably best to clean up as much as possible afterwards in the interest of keeping the image as lean as possible

**Comment by jeremykross** [comment]
Cleaning up the ruby packages brings it down to ~376 MB.

@normanjoyner , why are we including build-base, python-dev, and git in the image?  I assume build-base is for (at least) node-gyp during the npm install.

If I remove those packages as well it brings our size down to around ~176 MB but I dunno if that's actually safe to do or not.

**Comment by jeremykross** [comment]
@normanjoyner  - the dockerfile here is building at 173.5 MB on my machine.  Please test, obviously.

**Pull request merged**
